services:
  - type: web
    name: jer-social-media
    runtime: node
    plan: free
    buildCommand: npm install --no-audit --no-fund && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
